# Generated by Django 4.2.21 on 2025-06-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_tags_alter_categories_options_alter_categories_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
        migrations.AlterModelTable(
            name='tags',
            table='tag',
        ),
    ]
