# Generated by Django 4.2.21 on 2025-06-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_favorite_options_favorite_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='material',
            field=models.CharField(blank=True, max_length=150, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='products',
            name='size',
            field=models.CharField(blank=True, max_length=50, verbose_name='Размер'),
        ),
    ]
